---
#<% require 'poise_boiler' %>
<%= PoiseBoiler.kitchen %>

driver:
  name: zone
  transport:
    name: ssh
    host: 104.130.169.92
    # host: 192.168.42.200
    user: kantrn
    key_files: /Users/coderanger/.ssh/id_rsa
    sudo: true

platforms:
- name: solaris
